apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth-demo
  template:
    metadata:
      labels:
        app: auth-demo
    spec:
      containers:
        - name: auth-demo #name of containers
          image: odonataprime/auth:latest  #image of authorization 
          imagePullPolicy: Always
          ports:
            - name: httpd
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  sessionAffinity: ClientIP
  selector: 
    app: auth-demo
  type: ClusterIP
  clusterIP: 10.106.44.01 #fixed in cluster IP of the authorization service
  ports:
    - port: 5001
      targetPort: 8000

