apiVersion: v1
kind: Pod
metadata:
  name: pvc-client-pod
spec:
  containers:
    - name: pvc-client-container
      command: ['tail', '-f', '/dev/null']
      image: alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: data
          mountPath: /data/
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-pvc
