apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/chentianshi/Documents/postgres/data
  storageClassName: k8s-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: k8s-hostpath 
