apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth.fullname" . }}
spec:
  sessionAffinity: {{ .Values.sessionAffinity }}
  selector: {{- include "auth.selectorLabels" . | nindent 8 }}
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.tport }}
      targetPort: {{ .Values.service.port }}
