apiVersion: v1
kind: Service
metadata:
  name: {{ include "containerization.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.tport }}
      targetPort: {{ .Values.service.port }}
  selector: {{- include "containerization.selectorLabels" . | nindent 8 }}
