apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres-service # Sets the service name
  labels:
    app: postgres # Defines app to create service for
spec:
  type: ClusterIP # Sets the service type
  ports:
    - port: 5432 # Sets the port to run the postgres application
  clusterIP: 10.106.44.03
  selector: 
    app: postgres
