apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx-server #name of containers
          image: odonataprime/server  #image of authorization 
          imagePullPolicy: Always
          ports:
            - name: httpd
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: demoapi-secret
              mountPath: /opt/certs
              readOnly: true
      volumes:
        - name: demoapi-secret
          secret:
            secretName: temp-demoapi-tls-secret