apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  sessionAffinity: ClientIP
  selector: 
    app: nginx-server
  type: LoadBalancer
  clusterIP: 10.106.44.10
  ports:
    - port: 5000
      targetPort: 443
