apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: main-demo
  template:
    metadata:
      labels:
        app: main-demo
    spec:
      containers:
        - name: main-demo #name of containers
          image: odonataprime/shortener:latest  #image of authorization 
          imagePullPolicy: Always
          ports:
            - name: httpd
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  sessionAffinity: ClientIP
  selector: 
    app: main-demo
  type: LoadBalancer
  clusterIP: 10.106.44.02 #fixed in cluster IP of the main service
  ports:
    - port: 5002
      targetPort: 8000